import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Marquee from "@/components/Marquee";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const NotoSerifBengali = Noto_Serif_Bengali({
  subsets: ["bengali"],
});

export const metadata = {
  title: "Bazar Dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${NotoSerifBengali} h-full antialiased`}
      data-theme="light">
      <body className="min-h-full flex flex-col">
        <Header />
        <Marquee />
        {children}
        <Footer />
        <ToastContainer />
      </body>
    </html>
  );
}
